runtime: python312
service: fiscal
entrypoint: gunicorn -b :$PORT xml_manager.wsgi:application --timeout 300

instance_class: F2

handlers:
# Serve static files
- url: /static
  static_dir: staticfiles/
  expiration: "1d"

# Serve favicon explicitly to avoid 404s
- url: /favicon\.ico
  static_files: staticfiles/favicon.ico
  upload: staticfiles/favicon\.ico
  expiration: "7d"

# Serve all other requests
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

env_variables:
  DJANGO_SETTINGS_MODULE: 'xml_manager.settings_production'
  PYTHONUNBUFFERED: 'true'

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 80
