version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: fiscal_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_pass123
      MONGO_INITDB_DATABASE: aviladevops_fiscal
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: fiscal_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=dev-secret-key-change-in-production
      - DJANGO_DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - USE_MONGODB=true
      - MONGODB_DATABASE=aviladevops_fiscal
      - MONGODB_CONNECTION_STRING=mongodb://admin:admin_pass123@mongodb:27017/aviladevops_fiscal?authSource=admin
      - CSRF_TRUSTED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data:
  static_volume:
  media_volume:
